serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::814322484930:role/KarpenterControllerRole-infra-developing-dev"

settings:
  clusterName: "infra-demo"

controller:
  resources:
    requests:
      cpu: 300m
      memory: 512Mi

affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
          - key: infra
            operator: In
            values:
            - apps
