---
apiVersion: karpenter.k8s.aws/v1beta1
kind: EC2NodeClass
metadata:
  name: default
  annotations:
    kubernetes.io/description: "Default EC2NodeClass"
spec:
  amiFamily: Bottlerocket
  role: "KarpenterNodeRole-infra-demo"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "infra-demo"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "infra-demo"
  tags:
    managed-by: karpenter
